// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmlxDbSofo0aNVqQdBcxzll23AP-Edu8',
    appId: '1:961861318765:web:28a3432d546321b3baa764',
    messagingSenderId: '961861318765',
    projectId: 'pingpong-e15d9',
    authDomain: 'pingpong-e15d9.firebaseapp.com',
    storageBucket: 'pingpong-e15d9.appspot.com',
    measurementId: 'G-VGJ237DDHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNapuNFlWb2Gk3pXaJSFGsBo7khqwszZA',
    appId: '1:961861318765:android:580aae2558e0471bbaa764',
    messagingSenderId: '961861318765',
    projectId: 'pingpong-e15d9',
    storageBucket: 'pingpong-e15d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsn784Wk_HVBDLeIG1syFKkAdPldKS5s4',
    appId: '1:961861318765:ios:836eda7f55cf51c9baa764',
    messagingSenderId: '961861318765',
    projectId: 'pingpong-e15d9',
    storageBucket: 'pingpong-e15d9.appspot.com',
    iosBundleId: 'com.example.pingpong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsn784Wk_HVBDLeIG1syFKkAdPldKS5s4',
    appId: '1:961861318765:ios:836eda7f55cf51c9baa764',
    messagingSenderId: '961861318765',
    projectId: 'pingpong-e15d9',
    storageBucket: 'pingpong-e15d9.appspot.com',
    iosBundleId: 'com.example.pingpong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHmlxDbSofo0aNVqQdBcxzll23AP-Edu8',
    appId: '1:961861318765:web:d53a9b739365ceedbaa764',
    messagingSenderId: '961861318765',
    projectId: 'pingpong-e15d9',
    authDomain: 'pingpong-e15d9.firebaseapp.com',
    storageBucket: 'pingpong-e15d9.appspot.com',
    measurementId: 'G-H5Y4Q1X8G1',
  );
}
